name: Deploy and Update on Release
on:
  release:
    types:
      - published

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build and Publish
        run: |
          dotnet build
          dotnet publish -o build-output

      - name: Package and Push NuGet Package to GitHub Packages
        run: |
          dotnet pack --configuration Release --output nupkg/
          nuget push nupkg/*.nupkg -Source https://nuget.pkg.github.com/The-Poolz/index.json -ApiKey ${{ secrets.GITHUB_TOKEN }}
