name: Deploy and Update on Release
on:
  release:
    types:
      - published

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build and Publish
        run: |
          dotnet build
          dotnet publish -o build-output

      - name: Extract version from tag
        id: get_version
        run: echo "##[set-output name=VERSION;]$(echo ${GITHUB_REF#refs/tags/v})"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Update .csproj file with the new version using PowerShell
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          [xml]$csproj = Get-Content -Path YourProject.csproj
          $csproj.Project.PropertyGroup.Version = $version
          $csproj.Save("$(PWD)/YourProject.csproj")
        shell: pwsh

      - name: Remove build-output from tracking (if previously tracked)
        run: git rm -r --cached build-output

      - name: Add changes to commit (excluding build-output)
        run: |
          git add .
          git reset build-output/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update project version
          title: "Update project version to ${{ steps.get_version.outputs.VERSION }}"
          body: "This PR updates the .csproj project version to ${{ steps.get_version.outputs.VERSION }}"
          branch: "update-version-${{ steps.get_version.outputs.VERSION }}"
          delete-branch: true
