name: Deploy and Update on Release
on:
  release:
    types:
      - published

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build and Publish
        run: |
          dotnet build

      - name: Extract version from tag
        id: get_version
        run: echo "##[set-output name=VERSION;]$(echo ${GITHUB_REF#refs/tags/v})"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Update .csproj file with the new version using PowerShell
        run: |
          $version = "${{ steps.get_version.outputs.VERSION }}"
          [xml]$csproj = Get-Content -Path poolz.finance.csharp.contracts.csproj
          $csproj.Project.PropertyGroup.Version = $version
          $csproj.Save("$(PWD)/poolz.finance.csharp.contracts.csproj")
        shell: pwsh

      - name: Add changes to commit
        run: |
          git add .

      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update project version
          title: "Update project version to ${{ steps.get_version.outputs.VERSION }}"
          body: "This PR updates the .csproj project version to ${{ steps.get_version.outputs.VERSION }}"
          branch: "update-version-${{ steps.get_version.outputs.VERSION }}"
          delete-branch: true

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ steps.create_pull_request.outputs.pull-request-number }}
          curl \
            -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge" \
            -d '{"merge_method": "squash"}'

      - name: Package and Push NuGet Package to GitHub Packages
        run: |
          dotnet pack --configuration Release --output nupkg/
          nuget push nupkg/*.nupkg -Source https://nuget.pkg.github.com/The-Poolz/index.json -ApiKey ${{ secrets.GITHUB_TOKEN }}
